"""empty message

Revision ID: 70ca02c3cd99
Revises: 
Create Date: 2020-05-23 17:07:51.816386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ca02c3cd99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(length=100), nullable=False),
    sa.Column('song_name', sa.String(length=200), nullable=False),
    sa.Column('artist_id', sa.String(length=100), nullable=True),
    sa.Column('artist_name', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('album_id', sa.String(length=100), nullable=True),
    sa.Column('album_name', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_id', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('listen_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
